VeterinariaFramework/Models/Mascota.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace VeterinariaFramework.Models
{
    [Table("Mascotas")]
    public class Mascota
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int MascotaId { get; set; }

        [Required]
        [MaxLength(150)]
        public string Nombre { get; set; }
        
        [Required]
        [MaxLength(150)]
        public string Raza { get; set; }

        [Required]
        [MaxLength(1)]
        public string Sexo { get; set; }

        [Required]
        public int UsuarioId { get; set; }

        [ForeignKey("UsuarioId")]
        public virtual Usuario Usuario { get; set; }
                               
        [NotMapped]
        private ICollection<HistoriaClinica> historiasClinicas = new List<HistoriaClinica>();
        public virtual ICollection<HistoriaClinica> HistoriasClinicas
        {
            get { return historiasClinicas; }
            set { historiasClinicas = value; }
        }

    }
}

VeterinariaFramework/Controllers/ColaboradorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Windows.Forms;
using VeterinariaFramework.Models;

namespace VeterinariaFramework.Controllers
{
    public class ColaboradorController : Controller
    {
        private readonly VeterinariaDbContext _dbContext;

        public ColaboradorController(VeterinariaDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        [HttpGet]
        // GET: Colaborador
        public ActionResult Index()
        {            
            return View(_dbContext.Colaboradores.ToList());            
        }

        [HttpGet]
        // GET: Colaborador/Details/5
        public ActionResult Details(int id)
        {
            Colaborador colaborador = _dbContext.Colaboradores.Find(id);
            if (colaborador == null)
            {
                return HttpNotFound();
            }
            return View(colaborador);
        }

        // POST: Colaborador/Create        
        public ActionResult Create()
        {         
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "nombre,apellido,cargo,especialidad,tipoDocumento,DocumentoIdentificacion")] Colaborador colaborador)
        {
            int documento;
            if (int.TryParse(colaborador.DocumentoIdentificacion.ToString(), out documento))
            {
                colaborador.DocumentoIdentificacion = documento;
                if (ModelState.IsValid)
                {
                    _dbContext.Colaboradores.Add(colaborador);
                    _dbContext.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            // Si no se puede convertir el valor ingresado a un número entero válido,
            // o si el modelo no es válido, redirecciona al usuario a la vista "Create"
            return View(colaborador);
        }

        // GET: Mascota/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Colaborador colaborador = _dbContext.Colaboradores.Find(id);
            if (colaborador == null)
            {
                return HttpNotFound();
            }
            return View(colaborador);
        }

        // POST: Colaborador/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,nombre,apellido,cargo,especialidad,tipoDocumento,DocumentoIdentificacion")] Colaborador colaborador)
        {
            int documento;
            if (int.TryParse(colaborador.DocumentoIdentificacion.ToString(), out documento))
            {
                colaborador.DocumentoIdentificacion = documento;
                if (ModelState.IsValid)
                {
                    _dbContext.Entry(colaborador).State = System.Data.Entity.EntityState.Modified;
                    _dbContext.SaveChanges();
                    return RedirectToAction("Index");
                }
            }

            // Si no se puede convertir el valor ingresado a un número entero válido,
            // o si el modelo no es válido, redirecciona al usuario a la vista "Create"
            return View(colaborador);
         }

        // GET: Mascota/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Colaborador colaborador = _dbContext.Colaboradores.Find(id);
            if (colaborador == null)
            {
                return HttpNotFound();
            }
            return View(colaborador);
        }


        // POST: Colaborador/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Colaborador colaborador = _dbContext.Colaboradores.Find(id);
            _dbContext.Colaboradores.Remove(colaborador);
            _dbContext.SaveChanges();
            return RedirectToAction("Index");
        }

























    }
}

VeterinariaFramework/Controllers/MascotaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VeterinariaFramework.Models;
using VeterinariaFramework.Resository;
using VeterinariaFramework.Resositorys;

namespace VeterinariaFramework.Controllers
{
    public class MascotaController : Controller
    {
        private readonly IMascotaRepository _mascotaRepository;
        private readonly IUsuarioRepository _usuarioRepository;
        public MascotaController(IMascotaRepository mascotaRepository, IUsuarioRepository usuarioRepository)
        {
            _mascotaRepository = mascotaRepository ?? throw new ArgumentNullException(nameof(mascotaRepository));
            _usuarioRepository = usuarioRepository ?? throw new ArgumentNullException(nameof(usuarioRepository));
        }
        // GET: Mascota
        public ActionResult Index()
        {
            var mascotas = _mascotaRepository.GetAllMascotas();
            return View(mascotas.ToList());
        }
        // GET: Mascota/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }            
            Mascota mascota = _mascotaRepository.GetMascotaById(id.Value);
            if (mascota == null)
            {
                return HttpNotFound();
            }
            return View(mascota);
        }
        // GET: Mascota/Create
        public ActionResult Create()
        {
            var usuarios = _usuarioRepository.GetAllUsuarios();
            ViewBag.UsuarioId = new SelectList(usuarios, "UsuarioId", "Nombre");
            return View();
        }
        // POST: Mascota/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MascotaId,Nombre,Raza,Sexo,UsuarioId")] Mascota mascota)
        {
            if (ModelState.IsValid)
            {
                _mascotaRepository.UpdateMascota(mascota);
                return RedirectToAction("Index");
            }

            var usuarios = _usuarioRepository.GetAllUsuarios();
            ViewBag.UsuarioId = new SelectList(usuarios, "UsuarioId", "Nombre", mascota.UsuarioId);
            return View(mascota);
        }

        // GET: Mascota/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }            
            Mascota mascota = _mascotaRepository.GetMascotaById(id.Value);
            if (mascota == null)
            {
                return HttpNotFound();
            }
            var usuarios = _usuarioRepository.GetAllUsuarios();
            ViewBag.UsuarioId = new SelectList(usuarios, "UsuarioId", "Nombre", mascota.UsuarioId);
            return View(mascota);
        }

        // POST: Mascota/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MascotaId,Nombre,Raza,Sexo,UsuarioId")] Mascota mascota)
        {
            if (ModelState.IsValid)
            {
                _mascotaRepository.UpdateMascota(mascota);
                return RedirectToAction("Index");
            }
            var usuarios = _usuarioRepository.GetAllUsuarios();
            ViewBag.UsuarioId = new SelectList(usuarios, "UsuarioId", "Nombre", mascota.UsuarioId);
            return View(mascota);
        }
        // GET: Mascota/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Mascota mascota = _mascotaRepository.GetMascotaById(id.Value);
            if (mascota == null)
            {
                return HttpNotFound();
            }
            return View(mascota);
        }

        // POST: Mascota/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id)
        {          
            _mascotaRepository.DeleteMascota(id.Value);
            return RedirectToAction("Index");
        }









        






        



    }
}

VeterinariaFramework/Views/Mascota/Create.cshtml
@model VeterinariaFramework.Models.Mascota

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Mascota</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Raza, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Raza, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Raza, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.UsuarioId, "Propietario", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UsuarioId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UsuarioId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.RadioButtonFor(model => model.Sexo, "0", new { id = "macho" }) <label for="macho">Macho</label>
            @Html.RadioButtonFor(model => model.Sexo, "1", new { id = "hembra" }) <label for="hembra">Hembra</label>
            @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-primary" />
            <a href="@Url.Action("Index", "Colaborador")" class="btn btn-success">Regresar al Listado</a>
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VeterinariaFramework/Views/Mascota/Delete.cshtml
@model VeterinariaFramework.Models.Mascota

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h3>Esta seguro que quiere eliminar este registro?</h3>
<div>
    <h4>Mascota</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Usuario.Nombre)
        </dt>

        <dd class = "form-control">
            @Html.DisplayFor(model => model.Usuario.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd class = "form-control">
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Raza)
        </dt>

        <dd class = "form-control">
            @Html.DisplayFor(model => model.Raza)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd class = "form-control">
            @Html.DisplayFor(model => model.Sexo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" /> |
            <a href="@Url.Action("Index")" class="btn btn-primary">Volver al listado</a>
        </div>
    }
</div>

VeterinariaFramework/Views/Mascota/Details.cshtml
@model VeterinariaFramework.Models.Mascota

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<div>
    <h4>Mascota</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Usuario.Nombre)
        </dt>

        <dd class = "form-control">
            @Html.DisplayFor(model => model.Usuario.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd class = "form-control">
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Raza)
        </dt>

        <dd class = "form-control">
            @Html.DisplayFor(model => model.Raza)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>
        <dd>
            @if (Convert.ToInt32(Model.Sexo) == 0)
            {
                <dd class = "form-control">Macho</dd>
            }
            else
            {
                <dd class = "form-control">Hembra</dd>
            }
        </dd>



    </dl>
</div>
<div>
   <a href="@Url.Action("Index")" class="btn btn-success">Regresar a la lista</a>
</div>

VeterinariaFramework/Views/Mascota/Edit.cshtml
@model VeterinariaFramework.Models.Mascota

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Modificar Mascota</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.MascotaId)

    <div class="form-group">
        @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Raza, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Raza, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Raza, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.UsuarioId, "Propietario", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("UsuarioId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.UsuarioId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.RadioButtonFor(model => model.Sexo, "0", new { id = "macho" }) <label for="macho">Macho</label>
            @Html.RadioButtonFor(model => model.Sexo, "1", new { id = "hembra" }) <label for="hembra">Hembra</label>
            @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-success">Guardar</button>
            <a href="@Url.Action("Index")" class="btn btn-primary">Volver al listado</a>
        </div>
    </div>
</div>
}



@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VeterinariaFramework/Views/Mascota/Index.cshtml
@model IEnumerable<VeterinariaFramework.Models.Mascota>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Lista de mascotas</h2>

<p>
    <a href="@Url.Action("Create")" class="btn btn-success">Crear mascota</a>
</p>
<table class="table table-striped">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Usuario.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Raza)
        </th>
        <th>
            Sexo
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Raza)
            </td>
            <td>
                @if (item.Sexo == "0")
                {
                    <span>Macho</span>
                }
                else if (item.Sexo == "1")
                {
                    <span>Hembra</span>
                }
                else
                {
                    <span>Desconocido</span>
                }
            </td>
            <td>
                <a href="@Url.Action("Edit", new { id=item.MascotaId })" class="btn btn-primary">Modificar</a>
                <a href="@Url.Action("Details", new { id=item.MascotaId })" class="btn btn-info">Detalles</a>
                <a href="@Url.Action("Delete", new { id=item.MascotaId })" class="btn btn-danger">Borrar</a>         
            </td>
        </tr>
    }

</table>